project_id = "fmucxrtpiqxnfgvamjlo"

[functions.generate-lyrics]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.generate-music-suno]
verify_jwt = false

[functions.check-music-status]
verify_jwt = false

[functions.save-music-selection]
verify_jwt = false

[functions.generate-caption]
verify_jwt = false

[functions.generate-personal-message]
verify_jwt = false

[functions.analyze-lyrics-for-music]
verify_jwt = false