import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { caption, lyrics } = await req.json();
    console.log('Generate personal message function called');
    console.log('Input received:', { caption, lyrics: lyrics?.substring(0, 100) + '...' });

    if (!caption) {
      throw new Error('Caption is required');
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    const systemPrompt = `# Промт для создания текста обратной стороны открытки А6

## Системный промт:

**Ты - эксперт по созданию персональных посланий для обратной стороны открыток. Твоя задача - на основе заголовка лицевой части и слов песни создать теплое, личное послание (50-80 слов), которое объясняет подарок-песню и передает глубокие чувства отправителя.**

## Алгоритм работы:

### 1. Анализ входных данных:
- **Заголовок лицевой части** - ключевая эмоция и повод
- **Текст песни** - образы, метафоры, настроение для вдохновения
- **Контекст отношений** - определить близость отношений (семья, друзья, коллеги)

### 2. Структура послания:

**Формула:** [Личное обращение] + [Метафора/образ из песни] + [Объяснение QR-кода] + [Пожелание/благословение]

**Обязательные элементы:**
- Персональное обращение по имени
- Упоминание QR-кода и песни внутри
- Связь между песней и получателем
- Теплые пожелания или благословения

### 3. Стилистические особенности:

**🎵 Музыкальные метафоры:**
- "мелодия души", "твоя песня", "звучит в сердце"
- "каждая нота", "гармония жизни", "ритм счастья"

**🌟 Персональные образы:**
- Связать качества человека с элементами песни
- Использовать профессию, хобби, особенности характера
- Включить возраст, интересы (если уместно)

**💝 Эмоциональные акценты:**
- Искренность и теплота
- Признание уникальности получателя
- Надежда на будущее

### 4. Технические требования:

**Длина:** 50-80 слов (2-4 предложения)
**Тон:** Теплый, личный, искренний
**Язык:** Тот же, что и в заголовке лицевой части
**Обязательно:** Упоминание QR-кода и песни

### 5. Избегать:
- Формальных фраз без эмоций
- Слишком сложных метафор
- Банальных поздравлений
- Прямого цитирования текста песни
- Превышения лимита слов

---

## Формат ответа:

**На выходе только готовый текст послания (50-80 слов) без дополнительных пояснений.**`;

    const userPrompt = `Заголовок лицевой части: ${caption}

Текст песни:
${lyrics || 'Не указан'}

Создай персональное послание для обратной стороны открытки.`;

    console.log('Calling Lovable AI...');

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Lovable AI error:', response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded. Please try again later.' }), 
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: 'Payment required. Please add credits to your Lovable AI workspace.' }), 
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      throw new Error(`AI request failed: ${response.status} ${errorText}`);
    }

    const data = await response.json();
    const personalMessage = data.choices[0]?.message?.content?.trim();

    if (!personalMessage) {
      throw new Error('No message generated by AI');
    }

    console.log('Personal message generated successfully');
    console.log('Message length:', personalMessage.length);

    return new Response(
      JSON.stringify({ personalMessage }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in generate-personal-message function:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error occurred' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
