// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmucxrtpiqxnfgvamjlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtdWN4cnRwaXF4bmZndmFtamxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDMwMzMsImV4cCI6MjA2Njc3OTAzM30.rmTw7kmuAX6AWU3d8PNa6LFGn_u8vJ-EiDLgHlVFpDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});